name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_session6
      id: test_session6
      uses: autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 250
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: autograding-grading-reporter@v1
      env:
        TEST_SESSION5_RESULTS: "${{steps.test_session6.outputs.result}}"
      with:
        runners: test_session6
